CONFIG_ZMK_STUDIO=y
# 本番ファームウェアではStudio Lockを既定の有効状態にします。
# 開発用だけbuild.yamlのcmake-argsからLockを無効化します。

# DYA Studioで既定キーマップとの差分を高速に読み取ります。
CONFIG_ZMK_FAST_KEYMAP=y
CONFIG_ZMK_FAST_KEYMAP_STUDIO_RPC=y
CONFIG_ZMK_FAST_KEYMAP_DEFAULT_LAYER=y

# キー以外の物理デバイスをDYA Studioのレイアウトへ表示します。
CONFIG_ZMK_PHYSICAL_LAYOUTS_FEATURE=y
CONFIG_ZMK_PHYSICAL_LAYOUTS_FEATURE_STUDIO_RPC=y

# Custom Studio RPCの要求を受信できるよう、推奨値まで拡張します。
CONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=128
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_LOW_MV=900

# CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
